ALTER TABLE "ReportSmsDailySummary"
  ADD COLUMN "totalCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "deadLetterCount" INTEGER NOT NULL DEFAULT 0;
